runtime: python
env: flex

runtime_config:
    python_version: 3

entrypoint: python main.py

# env: flex

# Use only a single instance, so that this local-memory-only chat app will work
# consistently with multiple users. To work across multiple instances, an
# extra-instance messaging system or data store would be needed.
manual_scaling:
  instances: 1

network:
  session_affinity: true

# handlers:
# - url: /index\.html
#   static_files: web-app/index.html
#   upload: web-app/index\.html

# - url: /web-app
  # static_dir: web-app
  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
# - url: /.*
  # script: auto